`buildElement` is deprecated
JetBrains/kotlin-wrappers pull request #1032
Opened 2021-12-06 20:24 UTC by sgrishchenko

cc @turansky @aerialist7

2021-12-06 20:26 UTC, turansky requested changes
Request discussion before PR

2021-12-07 13:19 UTC, Leonya commented
`renderEach` was deprecated and removed by mistake. It was first accidentally broken, and then it was assumed (incorrectly) that it never worked before. Victor knows the details.

2021-12-07 15:45 UTC, sgrishchenko commented
I have removed obsolete todo comments

2021-12-07 15:47 UTC, turansky approved these changes

2021-12-07 15:57 UTC, merged