Popper. Strict `PaddingType`, `OffsetType`, `TetherOffsetType` + factories
JetBrains/kotlin-wrappers pull request #1378
Opened 2022-03-31 17:54 UTC by stefanthaler

cc @turansky

2022-03-31 19:44 UTC, turansky requested changes

2022-03-31 19:44 UTC, turansky commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
> +) -> PaddingType
`Padding`?

2022-03-31 19:44 UTC, turansky commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
> +    options: OffsetsFunctionOptions,
Common name for type required

2022-03-31 19:44 UTC, turansky commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
> +    block: Padding.()->Unit
Invalid formatting

2022-03-31 19:44 UTC, turansky commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/PreventOverflow.ext.kt
> +): OffsetType =
Invalid result type

2022-03-31 19:44 UTC, turansky commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/PreventOverflow.ext.kt
> +    options: OffsetsFunctionOptions,
Missed common alias

2022-03-31 22:41 UTC, turansky requested changes

2022-03-31 22:41 UTC, turansky commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
> +package popper.core.modifiers
Missed new line

2022-04-01 07:52 UTC, stefanthaler commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
> +    options: OffsetsFunctionOptions,
What about `PositionOptions` ?

2022-04-01 07:55 UTC, stefanthaler commented on kotlin-popper/src/main/kotlin/popper/core/modifiers/PreventOverflow.ext.kt
> +    options: OffsetsFunctionOptions,
What for?

2022-04-04 13:46 UTC, turansky approved these changes

2022-04-04 13:48 UTC, merged