MUI 5.9.2
JetBrains/kotlin-wrappers pull request #1966
Opened 2023-04-09 17:35 UTC by aerialist7

2023-04-09 17:51 UTC, turansky requested changes

2023-04-09 17:51 UTC, turansky commented on kotlin-mui/src/jsMain/generated/mui/base/OptionUnstyled.types.kt
> +external interface OptionUnstyledType {
Looks like redundant

2023-04-09 17:51 UTC, turansky commented on kotlin-mui/src/jsMain/generated/mui/base/SelectUnstyled.types.kt
> +external interface SelectUnstyledType {
Looks like redundant

2023-04-09 18:03 UTC, lucgirardin commented
Why are upgrading to MUI 5.9.2 (released in July 2023) and not to (one of) the latest version of MUI?!?

2023-04-09 18:15 UTC, aerialist7 commented on kotlin-mui/src/jsMain/generated/mui/base/OptionUnstyled.types.kt
> +external interface OptionUnstyledType {
Fixed

2023-04-09 18:15 UTC, aerialist7 commented on kotlin-mui/src/jsMain/generated/mui/base/SelectUnstyled.types.kt
> +external interface SelectUnstyledType {
Fixed

2023-04-09 18:30 UTC, turansky approved these changes

2023-04-09 18:31 UTC, merged

2023-04-09 18:39 UTC, aerialist7 commented
> Why are upgrading to MUI 5.9.2 (released in July 2023) and not to (one of) the latest version of MUI?!?

Hi @lucgirardin, please be patient and wait for updates - work in progress.

2023-04-11 07:21 UTC, lucgirardin commented
> > Why are upgrading to MUI 5.9.2 (released in July 2022) and not to (one of) the latest version of MUI?!?
> 
> Hi @lucgirardin, please wait for updates - work in progress

Will exercise patience ;-)