CSSType. Experimental & non-standard pseudos support  [generated]
JetBrains/kotlin-wrappers pull request #2061
Opened 2023-06-25 12:36 UTC by aerialist7

2023-06-25 12:50 UTC, turansky requested changes

2023-06-26 08:02 UTC, aerialist7 commented on kotlin-csstype/src/jsMain/generated/csstype/NonStandardRuleBuilder.kt
> +interface NonStandardRuleBuilder<T : Any> : RuleBuilder<T> {
Done

2023-06-26 08:02 UTC, aerialist7 commented on kotlin-csstype/src/jsMain/generated/csstype/ExperimentalRuleBuilder.kt
> +interface ExperimentalRuleBuilder<T : Any> : RuleBuilder<T> {
Done

2023-06-26 09:24 UTC, turansky requested changes

2023-06-26 09:31 UTC, aerialist7 commented on kotlin-csstype/src/jsMain/generated/csstype/ExperimentalRuleBuilder.kt
> +        "::highlight()($selector)"(block)
Done

2023-06-26 09:32 UTC, aerialist7 commented on kotlin-csstype/src/jsMain/generated/csstype/NonStandardRuleBuilder.kt
> +    inline fun mozColorSwatchNonStandard(
Done

2023-06-26 10:54 UTC, merged

2023-06-26 12:04 UTC, aerialist7 commented
@Leonya, could you please make a release?