Use Gradle's platform instead of enforcedPlatform for BOM
JetBrains/kotlin-wrappers pull request #2092
Opened 2023-08-12 23:02 UTC by lppedd

This avoids warnings when publishing a KMP artifact.

2023-08-12 23:46 UTC, turansky requested changes
Will it works fine for application?

2023-08-13 10:07 UTC, lppedd commented
@turansky I've just tried setting up an executable browser app (with React, using the IJ wizard), and the BOM works as expected with `platform`.

However (I think it's unrelated) beware something was changed in the React types, and I get this:

![image](https://github.com/JetBrains/kotlin-wrappers/assets/19871649/9094c50a-29af-44fe-8e4e-c61022e75291)

2023-08-13 11:43 UTC, turansky commented
Modern browser is already here. :)
[Example of usage](https://github.com/karakum-team/kotlin-react-table-sample/blob/68ff06607e073c0d1132541007b929e9ae1b075f/src/main/kotlin/team/karakum/App.kt#L16).

2023-08-13 12:34 UTC, lppedd commented
Replace the imports as per the example and now it works fine. Guess the IJ wizard needs an update.

2023-08-13 13:51 UTC, turansky commented
For me wizard is fine in latest IDEA/Kotlin plugin

2023-08-14 07:27 UTC, sgrishchenko commented
There is also `kotlin-wrappers-bom/README.md` where `enforcedPlatform`  is mentioned.

2023-08-14 08:13 UTC, sgrishchenko approved these changes

2023-08-14 14:39 UTC, sgrishchenko commented
We have internal discussion about this change. I will mark this change as draft for a while.

2023-08-14 14:43 UTC, lppedd commented
Thanks for the update @sgrishchenko, sure, no problem.

2023-08-16 15:07 UTC, merged