Enable lock file
JetBrains/kotlin-wrappers pull request #2310
Opened 2024-07-20 20:43 UTC by sgrishchenko

We have a long story with `package-lock.json` in Kotlin Wrappers repository:

* In the beginning we wanted to make a contribution more comfortable and we removed `package-lock.json` at all.
* Then we realized that we needed to stabilize builds and we came up with NPM overrides workaround.

But the current state still does not provide enough amounts of stability for builds. In personal discussions often we face strange glitches in `node_modules` so our current strategy for troubleshooting: `gradle clean` + `package-lock.json` removing. It should not be so because it ruins all caches and the whole build stability. And the current approach leads us to "works on my machine" problem.

In this PR I propose to return to `package-lock.json`. From my point of view, it is the most robust approach to provide stable builds. Now NPM support in Kotlin Mutiplatform Gradle plugin becomes more mature. And even NPM itself becomes more mature and can resolve conflicts in `package-lock.json` automatically. Also `package-lock.json` is most simple and popular approach to stabilize NPM dependencies.

I tried to describe all common scenarios that can cause problems with `package-lock.json`. I tested these scenarios using my local environment, so probably they should work. If I missed something or you check these approaches and they don't for you, let's discuss them.

2024-07-20 20:44 UTC, sgrishchenko commented
cc @aerialist7 @porotkin

2024-07-20 20:56 UTC, sgrishchenko commented
Something went wrong, and the Gradle build failed exactly on  `package-lock.json` check :stuck_out_tongue_winking_eye:. I will move this PR to Draft state until I figure out what is happening.

2024-07-20 22:11 UTC, sgrishchenko commented
The problem was with Kotlin Wrappers. It seems that GitHub runs action on the branch after merging. So in the GitHub action environment I have v775 in root `package-lock.json` and v779 in the build directory. It might be a problem to store `package-lock.json` file into Git.

2024-08-01 10:07 UTC, turansky requested changes

2024-08-01 10:07 UTC, turansky commented on .github/workflows/lock.yml
> +name: Lock
About filenames:
* `package-lock.yml`
* `package-lock.md`

looks preferrable

2024-08-01 10:07 UTC, turansky commented on .github/workflows/lock.yml
> +name: Lock
name: Package lock?

2024-08-01 20:13 UTC, turansky approved these changes

2024-08-01 20:37 UTC, merged