Add Ring UI wrappers
JetBrains/kotlin-wrappers pull request #498
Opened 2021-06-28 17:54 UTC by aerialist7

@ilgonmic, @altavir, @turansky

2021-06-28 18:03 UTC, turansky requested changes

2021-06-28 18:03 UTC, turansky commented on kotlin-react-table/src/main/kotlin/react/table/GroupBy.kt
> +    val Aggregated: FC<CellProps<D, *>>
Fix required

2021-06-28 18:13 UTC, turansky approved these changes

2021-06-28 18:15 UTC, aerialist7 commented on kotlin-react-table/src/main/kotlin/react/table/GroupBy.kt
> +    val Aggregated: FC<CellProps<D, *>>
> Fix required

Done

2021-06-29 20:30 UTC, merged

2021-06-29 20:58 UTC, Leonya commented
Released in pre.214