`RRender` -> `Render`
JetBrains/kotlin-wrappers pull request #561
Opened 2021-07-18 19:27 UTC by aerialist7

cc @turansky @sgrishchenko

2021-07-18 19:32 UTC, turansky requested changes

2021-07-18 19:32 UTC, turansky commented on kotlin-react/src/main/kotlin/react/RBuilder.kt
> +typealias RRender = Render
Redundant?

2021-07-18 19:42 UTC, aerialist7 commented on kotlin-react/src/main/kotlin/react/RBuilder.kt
> +typealias RRender = Render
Fixed

2021-07-18 19:44 UTC, merged

2021-07-19 20:30 UTC, Leonya commented
Released in pre.219