Add `RefCallback`
JetBrains/kotlin-wrappers pull request #565
Opened 2021-07-19 19:47 UTC by aerialist7

cc @turansky @sgrishchenko

2021-07-19 20:11 UTC, turansky requested changes

2021-07-19 20:11 UTC, turansky commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +    fun ref(handler: RefCallback<*>) {
Redundant?

2021-07-19 20:11 UTC, turansky commented on kotlin-react/src/main/kotlin/react/RBuilder.kt
> +    fun ref(handler: RefCallback<*>) {
Redundant?

2021-07-19 20:16 UTC, aerialist7 commented on kotlin-react/src/main/kotlin/react/RBuilder.kt
> +    fun ref(handler: RefCallback<*>) {
Fixed

2021-07-19 20:16 UTC, aerialist7 commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +    fun ref(handler: RefCallback<*>) {
Fixed

2021-07-19 20:21 UTC, turansky approved these changes

2021-07-20 11:55 UTC, merged

2021-07-21 12:46 UTC, Leonya commented
Released in pre.220