Move `ReactKey` from `react-table` to `react`
JetBrains/kotlin-wrappers pull request #577
Opened 2021-07-28 18:38 UTC by aerialist7

cc @turansky @sgrishchenko

2021-07-28 18:42 UTC, turansky requested changes

2021-07-28 18:42 UTC, turansky commented on kotlin-react/src/main/kotlin/react/Props.kt
> +var RProps.key: ReactKey
One more place?

2021-07-28 18:42 UTC, turansky commented on kotlin-react/src/main/kotlin/react/Key.kt
> +typealias ReactKey = String
`Key` like in types?

2021-07-28 18:43 UTC, aerialist7 commented on kotlin-react/src/main/kotlin/react/Key.kt
> +typealias ReactKey = String
Done

2021-07-28 18:52 UTC, aerialist7 commented on kotlin-react/src/main/kotlin/react/Props.kt
> +var RProps.key: ReactKey
OK

2021-07-28 18:56 UTC, turansky approved these changes

2021-07-28 19:21 UTC, merged

2021-07-30 19:24 UTC, Leonya commented
Released in pre.223