`CSSBuilder` -> `CssBuilder`
JetBrains/kotlin-wrappers pull request #585
Opened 2021-07-31 20:50 UTC by aerialist7

cc @turansky @sgrishchenko

2021-07-31 21:03 UTC, turansky requested changes

2021-07-31 21:03 UTC, turansky commented on kotlin-css/src/commonMain/kotlin/kotlinx/css/CssBuilder.kt
> +class CssBuilder(
`CSSBuilder` alias required (with `@Deprecate`)

2021-07-31 21:07 UTC, aerialist7 commented on kotlin-css/src/commonMain/kotlin/kotlinx/css/CssBuilder.kt
> +class CssBuilder(
Fixed

2021-07-31 21:11 UTC, turansky approved these changes

2021-08-01 15:26 UTC, Leonya commented
I'm sorry, it's a useless change and I'm not accepting it.

2021-08-01 19:40 UTC, aerialist7 commented
> I'm sorry, it's a useless change and I'm not accepting it.

Hm... Why useless? There is a coding convention rule for such cases.

https://developer.android.com/kotlin/style-guide#camel_case

2021-08-01 20:38 UTC, Leonya commented
Yes, sure there is. I didn't mind renaming `RState` and such because we aren't using them too much directly. `CSSBuilder` is a different story, it has hundreds of usages in our codebase and I simply don't want to rename them because of coding conventions. Some things are named imperfectly, let's just accept that. I have had this discussion with @turansky already and I can repeat my opinion: I appreciate your contributions, but I would really love to see a different ratio of useful, meaningful changes to "making the codebase pretty" changes. Right now we have maybe one or two useful changes per dozen of those that belong to the second category. Again, I do appreciate your contributions but you have to understand me as well: I am spending considerable time verifying the changes you've made and adapting my codebase to not have any deprecated symbols. Do I feel that I'm spending my time well? Well, I'm very sorry, but I just don't. If you want to create "perfect" Kotlin wrappers for JS libraries then maybe you should be doing this elsewhere. But if you want to be contributing to a JetBrains repository, then you need to the fact that not all of your PRs will be merged.

2021-08-02 09:00 UTC, merged

2021-08-02 09:37 UTC, Leonya commented
We have decided that we'll be refactoring `CSSBuilder` and `StyledElement` soon, so OK, let's rename it as well.

2021-09-08 21:21 UTC, xian commented
Uhhh... could you at least leave a deprecated `CSSBuilder` class sitting around for a while? My project depends on libraries which are now broken because of the rename. Super annoying.

2021-09-08 21:23 UTC, xian commented
@aerialist7 / @Leonya — in hopes someone will see this comment/https://github.com/JetBrains/kotlin-wrappers/pull/585#issuecomment-915581244 since I can't reopen the issue.

2021-09-08 23:04 UTC, turansky commented
@xian `CssBuilder` was changed with many other things and removed in #662 after **15** releases
Deprecated - `pre.224`
Removed - `pre.238`
 
Old `CSSBuilder` usage in library - incompatibility signal (library update required in any case)

cc @sgrishchenko