Support history in `RouterProps`
JetBrains/kotlin-wrappers pull request #587
Opened 2021-07-31 21:20 UTC by aerialist7

Closes #99 

cc @turansky @sgrishchenko

2021-07-31 21:26 UTC, turansky requested changes

2021-07-31 21:26 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
> +    var history: dynamic /*BrowserHistory*/
`BrowserHistory` exists in this repo

2021-08-01 08:19 UTC, aerialist7 commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
> +    var history: dynamic /*BrowserHistory*/
Fixed

2021-08-01 11:13 UTC, merged

2021-08-02 09:36 UTC, Leonya commented
Released in pre.224