Ring UI Wrapper: Add Checkbox component
JetBrains/kotlin-wrappers pull request #593
Opened 2021-08-02 14:55 UTC by Neitex

2021-08-02 15:09 UTC, turansky requested changes

2021-08-02 15:09 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/Checkbox.kt
> +    var containerStyle: Object
`dynamic` preferred, while interface not declared

2021-08-02 17:06 UTC, turansky approved these changes

2021-08-02 18:10 UTC, merged

2021-08-02 18:13 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/Checkbox.kt
> +    var containerStyle: Object
`CssProperties` can be declared in comment for property for future

2021-08-03 09:19 UTC, Leonya commented
Released in pre.225