Strict children
JetBrains/kotlin-wrappers pull request #604
Opened 2021-08-08 16:32 UTC by sgrishchenko

2021-08-08 19:12 UTC, turansky requested changes

2021-08-08 19:12 UTC, turansky commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +            childList.add(ReactNode(content.toString()))
`+` ?

2021-08-08 19:12 UTC, turansky commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +            childList.add(ReactNode(entity.text))
`+` ?

2021-08-08 19:12 UTC, turansky commented on kotlin-react/src/main/kotlin/react/ReactNode.kt
> +fun ReactNode(string: String): ReactNode =
It must be removed after #603

2021-08-08 19:15 UTC, turansky commented on kotlin-react/src/main/kotlin/react/RBuilder.kt
> +        childList.add(ReactNode(this))
`child(ReactNode(this))`?

2021-08-08 19:43 UTC, sgrishchenko commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +            childList.add(ReactNode(content.toString()))
fixed

2021-08-08 19:43 UTC, sgrishchenko commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +            childList.add(ReactNode(entity.text))
fixed

2021-08-08 19:47 UTC, sgrishchenko commented on kotlin-react/src/main/kotlin/react/RBuilder.kt
> +        childList.add(ReactNode(this))
both `unaryPlus` operators are fixed

2021-08-08 20:13 UTC, turansky commented on kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> +            +ReactNode(entity.text)
`+entity.text`?

2021-08-09 09:10 UTC, merged

2021-08-09 09:25 UTC, Leonya commented
Released in pre.229