Cleanup `gradle.properties`
JetBrains/kotlin-wrappers pull request #650
Opened 2021-08-22 17:33 UTC by turansky

* Remove redundant comments
* Group properties

cc @sgrishchenko @aerialist7

2021-08-22 18:46 UTC, Leonya requested changes

2021-08-22 18:46 UTC, Leonya commented on gradle.properties
> -# https://github.com/Kotlin/kotlinx.html/releases
Please keep this line

2021-08-22 18:46 UTC, Leonya commented on gradle.properties
> -# https://github.com/Kotlin/kotlinx.serialization/releases
And this one too.

2021-08-22 18:53 UTC, turansky commented on gradle.properties
> -# https://github.com/Kotlin/kotlinx.html/releases
Done

2021-08-22 18:53 UTC, turansky commented on gradle.properties
> -# https://github.com/Kotlin/kotlinx.serialization/releases
Done

2021-08-22 19:11 UTC, merged

2021-08-23 14:50 UTC, Leonya commented
Released in pre.235