[ring-ui] Add Footer component
JetBrains/kotlin-wrappers pull request #659
Opened 2021-08-24 17:13 UTC by Neitex

``` FooterItem ``` and ``` FooterDataItem ``` are called so because in Ring UI they are referred to as "item":
```js
function renderItem(item) {
    if (isValidElement(item)) {
      return item;
    }
// ...
```
```js
const element = (item.copyright ? copyright(item.copyright) : '') + (item.label || item);
```
```js
FooterLine.propTypes = {
  item: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.array,
    PropTypes.string
  ])
};
```

2021-08-24 21:47 UTC, turansky requested changes

2021-08-24 21:47 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/Footer.kt
> +
`FoterProps` must be here (before component)

2021-08-24 21:47 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +external interface FooterItem {
`IFooterItem`?

2021-08-24 21:47 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +external interface FooterDataItem : FooterItem {
And `FooterItem: IFooterItem`

2021-08-24 21:47 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +external interface FooterItem {
sealed?

2021-08-24 21:56 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +inline fun FooterItem(string: String): FooterItem = string.unsafeCast<FooterItem>()
New line after `=`?

2021-08-24 22:17 UTC, turansky requested changes

2021-08-24 22:17 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +package by.enrollie.eversity_web.components
`ringui`?

2021-08-24 22:17 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +    //Empty, as Footer props accept only plain arrays of either Any (it will convert it into String), either FooterItem
Comment can be removed

2021-08-24 22:17 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +inline fun FooterItem(string: String): IFooterItem =
`fun IFooterItem`?

2021-08-24 22:17 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/Footer.kt
> +//It seems that FooterColumn and FooterLine are not supposed to be used outside of Footer itself (in other words, only Footer should use them)
Redundant comment?

2021-08-24 22:17 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/Footer.kt
> +// https://github.com/JetBrains/ring-ui/blob/master/components/footer/footer.js
Redundant comment?

2021-08-24 22:18 UTC, Neitex commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +package by.enrollie.eversity_web.components
Already fixed

2021-08-24 22:34 UTC, turansky requested changes

2021-08-24 22:34 UTC, turansky commented on kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt
> +sealed external interface IFooterItem {
Empty body can be removed

2021-08-24 22:39 UTC, turansky approved these changes

2021-08-25 07:00 UTC, merged

2021-08-25 16:23 UTC, Leonya commented
Released in pre.237