`jsObject` deprecation in favour of `jso`
JetBrains/kotlin-wrappers pull request #678
Opened 2021-08-29 17:31 UTC by aerialist7

cc @turansky @sgrishchenko

2021-08-29 17:51 UTC, turansky requested changes

2021-08-29 17:51 UTC, turansky commented on kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
> +@Deprecated(
After next release please

2021-08-29 17:51 UTC, turansky commented on kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
> +@Deprecated(
After next release please

2021-08-29 17:51 UTC, turansky commented on kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
> +@Suppress("NOTHING_TO_INLINE")
On file please

2021-08-29 18:04 UTC, aerialist7 commented on kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
> +@Deprecated(
Ok

2021-08-29 18:04 UTC, aerialist7 commented on kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
> +@Deprecated(
Sure

2021-08-29 18:04 UTC, aerialist7 commented on kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
> +@Suppress("NOTHING_TO_INLINE")
Done

2021-08-29 19:05 UTC, turansky approved these changes

2021-08-29 19:05 UTC, turansky commented on examples/src/main/kotlin/example/main.kt
> +import kotlin.collections.set
Redundant import?

2021-08-30 04:15 UTC, aerialist7 commented on examples/src/main/kotlin/example/main.kt
> +import kotlin.collections.set
Seems yes

2021-08-30 06:46 UTC, merged

2021-08-31 19:45 UTC, Leonya commented
Released in pre.240