Builder pattern is used for `useRouteMatch` and `matchPath`
JetBrains/kotlin-wrappers pull request #694
Opened 2021-08-31 20:13 UTC by sgrishchenko

@turansky @aerialist7

2021-08-31 20:18 UTC, turansky requested changes

2021-08-31 20:18 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/MatchOptions.kt
> +external interface ExtraMatchOptions {
Discussion required

2021-09-01 18:08 UTC, sgrishchenko commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/MatchOptions.kt
> +external interface ExtraMatchOptions {
All notes after discussion are fixed

2021-09-01 18:33 UTC, turansky approved these changes

2021-09-01 18:33 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.ext.kt
> +    return matchPath(pathName, options, parent)
It can be one line

2021-09-01 18:33 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/Route.kt
> +external interface RouteProps : Props, MatchOptions {
Invalid replacement for `v5`

2021-09-01 18:42 UTC, turansky requested changes

2021-09-01 18:42 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.ext.kt
> +    return matchPath(pathName, jso<MatchOptions> { block() }, parent)
`jso(block)`?

2021-09-01 18:48 UTC, turansky approved these changes

2021-09-01 18:57 UTC, turansky approved these changes

2021-09-01 19:04 UTC, merged

2021-09-04 08:41 UTC, Leonya commented
Released in pre.241