Router: "raw" prefix is removed for low-level wrappers
JetBrains/kotlin-wrappers pull request #695
Opened 2021-08-31 20:18 UTC by sgrishchenko

@turansky @aerialist7

2021-08-31 20:26 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.kt
>      options: MatchOptions?,
definedExternally?

2021-08-31 20:35 UTC, sgrishchenko commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.kt
>      options: MatchOptions?,
yea, thanks, fixed

2021-08-31 20:57 UTC, turansky requested changes

2021-08-31 20:57 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.ext.kt
>      if (path.isEmpty()) {
Never called :)

2021-08-31 21:00 UTC, sgrishchenko commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.ext.kt
>      if (path.isEmpty()) {
fixed

2021-08-31 21:05 UTC, turansky approved these changes

2021-08-31 21:08 UTC, merged

2021-09-04 08:41 UTC, Leonya commented
Released in pre.241