Children are provided for RouteProps, render prop is deprecated
JetBrains/kotlin-wrappers pull request #697
Opened 2021-09-01 18:17 UTC by sgrishchenko

@turansky @aerialist7

2021-09-01 18:41 UTC, turansky requested changes

2021-09-01 18:41 UTC, turansky commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.legacy.kt
> +    render: RBuilder.() -> Unit,
`Render`?

2021-09-01 19:01 UTC, turansky approved these changes

2021-09-01 19:05 UTC, sgrishchenko commented on kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.legacy.kt
> +    render: RBuilder.() -> Unit,
fixed

2021-09-01 19:06 UTC, merged

2021-09-04 08:41 UTC, Leonya commented
Released in pre.241