`Dependencies` type alias is introduced, `RDependenciesArray` is deprecated
JetBrains/kotlin-wrappers pull request #837
Opened 2021-10-03 17:31 UTC by sgrishchenko

cc @turansky @aerialist7

2021-10-03 17:35 UTC, turansky requested changes

2021-10-03 17:35 UTC, turansky commented on kotlin-react/src/main/kotlin/react/Dependencies.kt
> +typealias RDependenciesArray = Dependencies
In separate file please

2021-10-03 17:46 UTC, sgrishchenko commented on kotlin-react/src/main/kotlin/react/Dependencies.kt
> +typealias RDependenciesArray = Dependencies
fixed

2021-10-03 17:47 UTC, turansky approved these changes

2021-10-03 17:48 UTC, merged

2021-10-04 09:34 UTC, Leonya commented
Released in pre.252